export const SEARCH_FOCUS = 'headear/SEARCH_FOCUS'
export const SEARCH_BLUR = 'headear/SEARCH_BLUR'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'
export const SEARCH_MOUSE_ENTER = 'header/SEARCH_MOUSE_ENTER'
export const SEARCH_MOUSE_LEAVE = 'header/SEARCH_MOUSE_LEAVE'
